CREATE VIEW cleaned.JobCharge AS
WITH JobCharge AS (
    SELECT
    [JR_PK],
	[JR_IsValid],
	[JR_JH],
	[JR_GE],
	[JR_GB],
	[JR_JH_InternalJob],
	[JR_GE_InternalDept],
	[JR_GB_InternalBranch],
	[JR_LineCFX],
	[JR_AC],
	[JR_Desc],
	[JR_OH_CostAccount],
	[JR_CostRated],
	[JR_CostRatingOverride],
	[JR_CostRatingOverrideComment],
	[JR_OSCostAmt],
	[JR_AgentDeclaredCostAmt],
	[JR_LocalCostAmt],
	[JR_RX_NKCostCurrency],
	[JR_OSCostExRate] ,
	[JR_AT_CostGSTRate],
	[JR_OSCostGSTAmt] ,
	[JR_A9_CostVATClass],
	[JR_AW_CostWHTRate],
	[JR_OSCostWHTAmt] ,
	[JR_EstimatedCost] ,
	[JR_APLinePostingStatus],
	[JR_CostReference],
	[JR_APInvoiceNum],
	[JR_APInvoiceDate],
	[JR_APNumberOfSupportingDocuments],
	[JR_PaymentDate],
	[JR_PaymentType],
	[JR_ChequeNo],
	[JR_AK],
	[JR_AB],
	[JR_AL_APLine],
	[JR_DeclaredOSCostAmt],
	[JR_ProFormaCost],
	[JR_OH_SellAccount],
	[JR_OA_SellInvoiceAddress],
	[JR_OC_SellInvoiceContact],
	[JR_RX_NKSellCurrency],
	[JR_OSSellExRate],
	[JR_OSSellAmt],
	[JR_A9_SellVATClass],
	[JR_AgentDeclaredSellAmt],
	[JR_LocalSellAmt],
	[JR_SellRated],
	[JR_SellRatingOverride],
	[JR_SellRatingOverrideComment],
	[JR_AT_SellGSTRate], 
	[JR_AW_SellWHTRate], 
	[JR_OSSellWHTAmt],
	[JR_SellReference], 
	[JR_AL_ARLine], 
	[JR_AL_CFXLine], 
	[JR_EstimatedRevenue],
	[JR_IsIncludedInProfitShare],
	[JR_ChargeType], 
	[JR_MarginPercentage],
	[JR_ARNumberOfSupportingDocuments],
	[JR_InvoiceType], 
	[JR_ProFormaRevenue],
	[JR_PreventInvoicePrintGrouping],
	[JR_DisplaySequence],
	[JR_ARLinePostingStatus], 
	[JR_OrderReference], 
	[JR_OP_Product], 
	[JR_ProductQuantity],
	[JR_E6], 
	[JR_GC], 
	[JR_CostGovtChargeCode], 
	[JR_E6_GatewaySellHeader], 
	[JR_JR_RevenueLine], 
	[JR_LineType], 
	[JR_RX_NKSellInvoiceCurrency], 
	[JR_SellGovtChargeCode], 
	[JR_CostTaxDate], 
	[JR_SellTaxDate], 
	[JR_IsCostTaxAmountOverridden],
	[JR_APDocumentReceivedDate],
	[JR_AutoVersion],
	[JR_CostPlaceOfSupply], 
	[JR_CostPlaceOfSupplyType], 
	[JR_SellPlaceOfSupply], 
	[JR_SellPlaceOfSupplyType], 
	[JR_CostSupplyType], 
	[JR_SellSupplyType], 
	[JR_SystemCreateTimeUtc], 
	[JR_SystemCreateUser], 
	[JR_SystemLastEditTimeUtc],
	[JR_SystemLastEditUser],
	[JR_CAL_APLine],
	[JR_CAL_ARLine],
	[JR_GB_CostTaxBranch], 
	[JR_GB_SellTaxBranch], 
	[JR_IsAPCashAdvance],
	[JR_IsARCashAdvance],
	[JR_IsSpotCost]
    FROM [cargowise_dk_wrld].[JobCharge]
)
SELECT * FROM JobCharge;

	
