WITH Jobs_AR AS (
    SELECT
        A.AL_PostDate as "AL_AR_PostDate",
        A.AL_PK,
        A.AL_RevRecognitionType as "AL_AR_RevRecognitionType",
        B.JR_PK,
        B.JR_GE,
        B.JR_GB,
        B.JR_AC,
        B.JR_OH_CostAccount,
        B.JR_LocalCostAmt,
        B.JR_PaymentDate,
        B.JR_OH_SellAccount,
        B.JR_LocalSellAmt,
        B.JR_ChargeType,
        B.JR_EstimatedCost,
        B.JR_EstimatedRevenue,
        B.JR_JH,
        C.D3_PK,
        C.D3_RecognitionType,
        C.D3_RecognitionDate,
        C.D3_JH,
        C.D3_SystemCreateTimeUtc,
        C.D3_SystemCreateUser,
        C.D3_SystemLastEditTimeUtc,
        C.D3_SystemLastEditUser,
        D.JH_JobNum,
        D.JH_Status,
        D.JH_A_JOP,
        D.JH_A_JCL,
        D.JH_OA_LocalChargesAddr,
        D.JH_OA_AgentCollectAddr,
        D.JH_GS_NKRepSales,
        D.JH_GS_NKRepOps,
        D.JH_JobType,
        D.JE,
        D.WKI,
        D.JS,
        D.TH,
        D.JH_PK,
        F.JS_ShipmentStatus,
        F.JS_RL_NKOrigin,
        F.JS_RL_NKDestination,
        F.JS_TransportMode,
        F.JS_ActualVolume,
        F.JS_UnitOfVolume,
        F.JS_ActualWeight,
        F.JS_UnitOfWeight,
        F.JS_ActualChargeable,
        F.JS_UnitFreightRate,
        F.JS_ShipmentType,
        F.JS_LoadingMeters,
        F.JS_RL_NKPlaceOfReceipt,
        F.JS_RL_NKPlaceOfDischarge
    FROM cleaned.AccTransactionLines as A
    LEFT JOIN cleaned.JobCharge as B ON UPPER(A.AL_PK) = UPPER(B.JR_AL_ARLine)
    LEFT JOIN cleaned.JobChargeRevRecognition as C on UPPER(C.D3_JH) = UPPER(B.JR_JH) AND UPPER(C.D3_RecognitionType) = UPPER(A.AL_RevRecognitionType)
    LEFT JOIN cargowise_dk_wrld.JobHeader as D ON UPPER(D.JH_PK) = UPPER(B.JR_JH)
    LEFT JOIN cleaned.JobShipment AS F ON UPPER(F.JS_PK) = UPPER(D.JS))

    SELECT * FROM Jobs_AR;
