-- SCOPE BRANCHES --

CREATE TABLE dbo.mad_branch (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(32) NOT NULL,
  name varchar(255) NULL,
  legalEntity_OID varchar(40) NOT NULL,
  partner_OID varchar(40) NOT NULL,
  timeZone varchar(48) NULL,
  organizationOID varchar(40) NOT NULL,
  singleClientCapable integer NOT NULL,
  receivesEmails integer NOT NULL,
  codeForNumberGen varchar(4) NULL,
  emailFinanceNotifications varchar(2000) NULL);

-- SCOPE CHARGE TYPES --

CREATE TABLE dbo.mad_charge_type (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(6) NOT NULL,
  transit integer NOT NULL,
  validityStart date NULL,
  validityEnd date NULL,
  localizedName_oid varchar(40) NULL,
  role varchar(32) NOT NULL,
  breakdownRule varchar(32) NOT NULL,
  organizationOID varchar(40) NOT NULL,
  voucherText_oid varchar(40) NULL,
  type varchar(32) NOT NULL,
  equalCost integer NOT NULL,
  ediCode varchar(24) NULL,
  validInReceivable integer NOT NULL,
  validInPayable integer NOT NULL,
  airFreightSurcharge integer NOT NULL,
  mainTransportRelated integer NOT NULL,
  calculationBasis varchar(32));

-- SCOPE EXCHANGE RATES --

CREATE TABLE dbo.mad_exc_rate (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  baseCurrency varchar(3) NOT NULL,
  directQuotation VARCHAR(1000) NOT NULL,
  rate decimal(18,9) NOT NULL,
  targetCurrency varchar(3) NOT NULL,
  type varchar(32) NOT NULL,
  unit integer NOT NULL,
  validFrom date NOT NULL,
  mad_currency_oid varchar(40) NOT NULL);

-- SCOPE COMPANIES --

CREATE TABLE dbo.mad_legal_entity (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(32) NOT NULL,
  name varchar(255) NULL,
  timeZone varchar(48) NOT NULL,
  lastOpenMonth date NULL,
  organization_OID varchar(40) NOT NULL,
  currency varchar(3) NOT NULL,
  supportTeam varchar(70) NULL,
  enableDocumentArchiveExport integer NOT NULL,
  jiraCustomer varchar(70) NULL,
  exportUploadedVoucherDocs integer NOT NULL,
  exportUploadedShipmentDocs integer NOT NULL,
  addressInterfaceEnabled integer NOT NULL,
  crmId varchar(36) NULL);

-- SCOPE PARTNERS  --

CREATE TABLE dbo.mad_partner (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(128) NOT NULL,
  name varchar(255) NULL,
  deactivated VARCHAR(1000) NOT NULL,
  labels VARCHAR(1000),
  urn varchar(128) NOT NULL,
  organizationOID varchar(40) NOT NULL,
  phoneNumber varchar(32) NULL,
  faxNumber varchar(32) NULL,
  eMailAddress varchar(64) NULL,
  webAddress varchar(255) NULL,
  taxIDNumber varchar(255) NULL,
  taxIDType varchar(32) NOT NULL,
  profileLabels varchar(2000) NULL,
  linked_crm varchar(128) NULL,
  chamberOfCommerceNumber varchar(255) NULL,
  dunsNumber varchar(9) NULL,
  lwi_addresstool_id varchar(128) NULL,
  cinType varchar(32) NULL,
  CIN varchar(255) NULL,
  locked integer NOT NULL 0,
  eoriNumber varchar(17) NULL,
  dunsAddress varchar(512) NULL,
  lastLookupUser varchar(512) NULL,
  lastLookupDate date NULL,
  lastQuickCheckUser varchar(512) NULL,
  lastQuickCheckDate date NULL,
  businessType varchar(32) NOT NULL,
  vatGroup_OID varchar(40) NULL,
  rexNumber varchar(35) NULL,
  lineOfBusiness_OID varchar(40) NULL,
  iossNumber varchar(12) NULL);

-- SCOPE PARTNER GROUPS -

CREATE TABLE dbo.mad_partner_group (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(128) NOT NULL,
  deactivated integer NOT NULL,
  organizationOID varchar(40) NOT NULL,
  name varchar(255) NULL,
  systemGroup integer NOT NULL);

-- SCOPE COUNTRIES --

CREATE TABLE dbo.mad_country (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(2) NOT NULL,
  EUMemberAsOf date NULL,
  alpha3 varchar(3) NULL,
  cityFormat varchar(32) NULL,
  currency varchar(3) NULL,
  iso3166_numeric varchar(3) NULL,
  postalCode varchar(3) NULL,
  timezone varchar(48) NULL,
  zipFormat varchar(32) NULL,
  name_OID varchar(40) NULL,
  deactivated integer NOT NULL,
  EUMemberUntil date NULL);

-- SCOPE PARTNER GROUP PARTNERS

CREATE TABLE dbo.mad_partner_group_partners (
  PARTNER_GROUP_OID varchar(40) NOT NULL,
  PARTNER_OID varchar(40) NOT NULL,
  PARTNER_POSITION integer NOT NULL);

-- SCOPE PARTNER PROFILES  --

CREATE TABLE dbo.mad_partner_profile_ids (
  MAD_PARTNER_OID varchar(40) NOT NULL,
  id varchar(255) NOT NULL,
  legalEntityOID varchar(40) NULL,
  profileOID varchar(40) NOT NULL,
  P_POSITION integer NOT NULL);

-- SCOPE UNLCODES --

CREATE TABLE dbo.mad_unlocode (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(5) NOT NULL,
  IATACode varchar(3) NULL,
  air VARCHAR(1000) NOT NULL,
  rail VARCHAR(1000) NOT NULL,
  sea VARCHAR(1000) NOT NULL,
  timeZone varchar(48) NULL,
  country_OID varchar(40) NULL,
  name_OID varchar(40) NULL,
  state_OID varchar(40) NULL,
  mainLocation_OID varchar(40) NULL,
  latitude varchar(32) NULL,
  longitude varchar(32) NULL,
  deactivated integer NOT NULL,
  airportName varchar(31) NULL,
  scheduleDCode varchar(4) NULL,
  scheduleKCode varchar(5) NULL);

-- SCOPE SHIPMENT LAST UPDATES --

CREATE TABLE dbo.rep_flat_order (
  OID varchar(40) NOT NULL,
  chargeableWeightAmount decimal(19,3) NULL,
  chargeableWeightUnit varchar(32) NULL,
  clerk varchar(128) NULL,
  consigneeCode varchar(128) NULL,
  consigneeName varchar(767) NULL,
  consigneeOID varchar(40) NULL,
  conveyanceType varchar(5) NULL,
  departureCode varchar(5) NULL,
  departureCountryOID varchar(40) NULL,
  departureUnlocodeOID varchar(40) NULL,
  destinationCode varchar(5) NULL,
  destinationCountryOID varchar(40) NULL,
  destinationUnlocodeOID varchar(40) NULL,
  economicDate date NULL,
  exportAgentCode varchar(128) NULL,
  exportAgentName varchar(128) NULL,
  exportAgentOID varchar(40) NULL,
  exportGatewayCode varchar(128) NULL,
  exportGatewayName varchar(128) NULL,
  exportGatewayOID varchar(40) NULL,
  grossWeightAmount decimal(19,3) NULL,
  grossWeightUnit varchar(32) NULL,
  importAgentCode varchar(128) NULL,
  importAgentName varchar(128) NULL,
  importAgentOID varchar(40) NULL,
  importGatewayCode varchar(128) NULL,
  importGatewayName varchar(128) NULL,
  importGatewayOID varchar(40) NULL,
  incoTerms varchar(3) NULL,
  incotermPlace varchar(127) NULL,
  lastUpdate datetime2(6) NOT NULL,
  moduleName varchar(35) NOT NULL,
  movementScope varchar(32) NULL,
  natureOfGoods varchar(512) NULL,
  orderDate date NULL,
  ordererCode varchar(128) NULL,
  ordererName varchar(767) NULL,
  ordererOID varchar(40) NULL,
  parentOID varchar(40) NULL,
  pieces integer NULL,
  salesPersonOID varchar(40) NULL,
  shipmentNumber varchar(35) NULL,
  shipmentType varchar(35) NULL,
  shipperCode varchar(128) NULL,
  shipperName varchar(767) NULL,
  shipperOID varchar(40) NULL,
  mainTransportCarrierCode varchar(128) NULL,
  mainTransportCarrierName varchar(255) NULL,
  mainTransportCarrierOID varchar(40) NULL,
  usi varchar(19) NULL,
  totalVolumeAmount decimal(19,3) NULL,
  totalVolumeUnit varchar(32) NULL,
  ETD_SDATE date NULL,
  ETD_STIME integer NULL,
  ETA_SDATE date NULL,
  ETA_STIME integer NULL,
  departureIATACode varchar(3) NULL,
  destinationIATACode varchar(3) NULL,
  orderURN varchar(128) NULL,
  orderMimeType varchar(255) NULL,
  branchOID varchar(40) NULL,
  branchCode varchar(32) NULL,
  carrierOID varchar(40) NULL,
  carrierCode varchar(128) NULL,
  carrierName varchar(128) NULL,
  sellingProductOID varchar(40) NULL,
  organizationOID varchar(40) NOT NULL,
  legalEntityOID varchar(40) NOT NULL,
  dgr integer NOT NULL,
  masterOID varchar(40) NULL,
  notifyCode varchar(128) NULL,
  notifyName varchar(767) NULL,
  notifyOID varchar(40) NULL,
  masterShipmentNumber varchar(35) NULL,
  cancelled integer NOT NULL,
  ATA_SDATE date NULL,
  ATA_STIME integer NULL,
  ATD_SDATE date NULL,
  ATD_STIME integer NULL,
  linerAgentCode varchar(128) NULL,
  linerAgentName varchar(128) NULL,
  linerAgentOID varchar(40) NULL,
  seaLoadingType varchar(32) NULL,
  vesselName varchar(128) NULL,
  voyage varchar(128) NULL,
  flight1 varchar(32) NULL,
  flight2 varchar(32) NULL,
  flight3 varchar(32) NULL,
  flight4 varchar(32) NULL,
  securityReason varchar(70) NULL,
  securityStatus varchar(32) NULL,
  specialCustomsInformation varchar(32) NULL,
  teu integer NULL,
  over18Ton integer NULL,
  consigneeDocumentAddressOID varchar(40) NULL,
  ordererDocumentAddressOID varchar(40) NULL,
  shipperDocumentAddressOID varchar(40) NULL,
  dealDate date NULL,
  salesPersonName varchar(100) NULL,
  placeOfDeliveryCode varchar(5) NULL,
  placeOfDeliveryCountryOID varchar(40) NULL,
  placeOfDeliveryUnlocodeOID varchar(40) NULL,
  placeOfReceiptCode varchar(5) NULL,
  placeOfReceiptCountryOID varchar(40) NULL,
  placeOfReceiptUnLocodeOID varchar(40) NULL,
  pickupTime_FromDate date NULL,
  pickupTime_FromTime integer NULL,
  pickupTime_ToDate date NULL,
  pickupTime_ToTime integer NULL,
  dropOffTime_FromDate date NULL,
  dropOffTime_FromTime integer NULL,
  dropOffTime_ToDate date NULL,
  dropOffTime_ToTime integer NULL,
  truckLicensePlate varchar(31) NULL,
  insuranceAmount decimal(20,3) NULL,
  insuranceCurrency varchar(3) NULL,
  loadingMetres decimal(9,2) NULL,
  ordererPostalAddressOID varchar(40) NULL,
  shipperPostalAddressOID varchar(40) NULL,
  consigneePostalAddressOID varchar(40) NULL,
  departureName varchar(255) NULL,
  destinationName varchar(255) NULL,
  placeOfReceiptName varchar(255) NULL,
  placeOfDeliveryName varchar(255) NULL,
  externalID varchar(64) NOT NULL,
  placeOfDeliveryIATACode varchar(3) NULL,
  placeOfReceiptIATACode varchar(3) NULL,
  mainTransportFreightTerm varchar(1) NULL,
  buyingProductOID varchar(40) NULL,
  warehouseCode varchar(128) NULL,
  warehouseName varchar(767) NULL,
  warehousePartnerOID varchar(40) NULL,
  terminalCode varchar(128) NULL,
  terminalName varchar(767) NULL,
  terminalPartnerOID varchar(40) NULL,
  remarks varchar(512) NULL,
  lineOfBusinessOID varchar(40) NULL,
  lineOfBusinessPartnerOID varchar(40) NULL,
  salesZoneCountryOID varchar(40) NULL,
  salesZoneZIPCode varchar(32) NULL,
  salesCommissionAmount decimal(20,3) NULL,
  salesCommissionCurrency varchar(3) NULL,
  hasActiveBlock integer NOT NULL,
  statisticalReference varchar(35) NULL,
  ownContainers integer NOT NULL,
  rq_pup_date date NULL,
  rq_pup_time integer NULL,
  rq_dlv_date date NULL,
  rq_dlv_time integer NULL,
  DOC_CLOSING_DATE date NULL,
  DOC_CLOSING_TIME integer NULL,
  freightAmount decimal(20,3) NULL,
  freightCurrency varchar(3) NULL,
  freightTerms varchar(1) NULL,
  otherChargesAmount decimal(20,3) NULL,
  otherChargesCurrency varchar(3) NULL,
  otherChargesTerms varchar(1) NULL,
  containerDepotOID varchar(40) NULL,
  containerDepotCode varchar(128) NULL,
  containerDepotName varchar(767) NULL,
  containerReturnDepotOID varchar(40) NULL,
  containerReturnDepotCode varchar(128) NULL,
  containerReturnDepotName varchar(767) NULL,
  co2Amount decimal(19,3) NULL,
  co2Unit varchar(32) NULL,
  co2eAmount decimal(19,3) NULL,
  co2eUnit varchar(32) NULL,
  co2wtwAmount decimal(19,3) NULL,
  co2wtwUnit varchar(32) NULL,
  compensationCostsAmount decimal(20,3) NULL,
  compensationCostsCurrency varchar(3) NULL,
  co2distanceAmount decimal(19,3) NULL,
  co2distanceUnit varchar(32) NULL,
  cancellationReasonOID varchar(40) NULL,
  std_sdate date NULL,
  std_stime integer NULL,
  sta_sdate date NULL,
  sta_stime integer NULL,
  vgm_closing_sdate date NULL,
  vgm_closing_stime integer NULL);


--  SCOPE JOB COSTINGS ESTIMATE --

CREATE TABLE dbo.vou_estimate_jc_entry (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  amount decimal(20,3) NULL,
  currency varchar(3) NULL,
  bookingDate date NOT NULL,
  costCenterOID varchar(40) NULL,
  economicDate date NULL,
  baseCurrency varchar(3) NULL,
  directQuotation integer NOT NULL,
  rate decimal(18,9) NULL,
  targetCurrency varchar(3) NULL,
  unit integer NOT NULL,
  income integer NOT NULL,
  JCNUMBER varchar(255) NULL,
  localCurrency varchar(3) NULL,
  orderMimeType varchar(255) NOT NULL,
  ORDER_OID varchar(40) NOT NULL,
  orderReference varchar(255) NULL,
  ownerOID varchar(40) NOT NULL,
  partnerOID varchar(40) NULL,
  type varchar(32) NOT NULL,
  chargeType_OID varchar(40) NOT NULL,
  accrualOID varchar(40) NOT NULL,
  accrualsLedger varchar(32) NULL,
  costLedger varchar(32) NULL,
  rootOrderOID varchar(40) NOT NULL,
  rootOrderMimeType varchar(255) NOT NULL,
  localAmount decimal(20,3) NULL,
  localAmountCur varchar(3) NULL,
  finalizationOID varchar(40) NULL,
  tariffOrderOID varchar(40) NULL);

-- SCOPE JOB COSTINGS --

CREATE TABLE dbo.vou_real_jc_entry (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  amount decimal(20,3) NULL,
  currency varchar(3) NULL,
  baseCurrency varchar(3) NULL,
  directQuotation integer NOT NULL,
  rate decimal(18,9) NULL,
  targetCurrency varchar(3) NULL,
  unit integer NOT NULL,
  JCNUMBER varchar(255) NULL,
  localCurrency varchar(3) NULL,
  ORDER_OID varchar(40) NOT NULL,
  ownerOID varchar(40) NOT NULL,
  type varchar(32) NOT NULL,
  chargeType_OID varchar(40) NOT NULL,
  mirroredChargeLineOID varchar(40) NOT NULL,
  VOU_VOUCHER_OID varchar(40) NOT NULL,
  voucherType varchar(32) NULL,
  orderReference varchar(255) NULL,
  orderMimeType varchar(255) NOT NULL,
  income integer NOT NULL,
  bookingDate date NOT NULL,
  partnerOID varchar(40) NULL,
  costCenterOID varchar(40) NULL,
  economicDate date NULL,
  glaNumber varchar(32) NULL,
  slaNumber varchar(32) NULL,
  rootOrderOID varchar(40) NOT NULL,
  rootOrderMimeType varchar(255) NOT NULL,
  localAmount decimal(20,3) NULL,
  localAmountCur varchar(3) NULL,
  taxKey varchar(32) NULL,
  taxAmount decimal(20,3) NULL,
  taxAmountCurrency varchar(3) NULL,
  localTaxAmount decimal(20,3) NULL,
  localTaxAmountCurrency varchar(3) NULL,
  finalizationOID varchar(40) NULL,
  tariffOrderOID varchar(40) NULL,
  externalReference varchar(255) NULL);

-- SCOPE INVOICES --

CREATE TABLE dbo.vou_voucher (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  costSpecification integer NULL,
  baseCurrency varchar(3) NULL,
  directQuotation VARCHAR(1000) NOT NULL,
  rate decimal(18,9) NULL,
  targetCurrency varchar(3) NULL,
  unit integer NOT NULL,
  currency varchar(3) NULL,
  v_language varchar(32) NULL,
  manuallyCreated VARCHAR(1000) NOT NULL,
  outgoing VARCHAR(1000) NOT NULL,
  remarks VARCHAR(1000),
  status varchar(32) NOT NULL,
  slaNumber varchar(32) NULL,
  subject varchar(255) NULL,
  totalAmount decimal(20,3) NULL,
  totalCurrency varchar(3) NULL,
  netAmount decimal(20,3) NULL,
  netCurrency varchar(3) NULL,
  roundingAmount decimal(20,3) NULL,
  roundingCurrency varchar(3) NULL,
  voucherType varchar(32) NULL,
  address_OID varchar(40) NULL,
  finalization_OID varchar(40) NULL,
  owner_OID varchar(40) NULL,
  cancelation_OID varchar(40) NULL,
  externalReference varchar(255) NULL,
  legalEntityOID varchar(40) NOT NULL,
  aggregatedVoucherOID varchar(40) NULL,
  originVoucherOID varchar(40) NULL,
  counterpartVoucherOID varchar(40) NULL,
  paymentType varchar(32) NOT NULL,
  paymentReference varchar(255) NULL,
  invoice integer NOT NULL,
  taxIDNumber varchar(255) NULL,
  taxIDType varchar(32) NOT NULL,
  paymentTerm_OID varchar(40) NULL,
  dueDate date NULL,
  debit integer NOT NULL,
  entryDate date NOT NULL,
  correctionVoucher integer NOT NULL,
  receiptNumber varchar(255) NULL,
  receiptPrintDate date NULL,
  manualEcoDate integer NOT NULL,
  bankAccount_OID varchar(40) NULL,
  voucherCreator varchar(128) NOT NULL,
  cfdiUsage varchar(4) NULL,
  depositAmount decimal(20,3) NULL,
  depositCurrency varchar(3) NULL,
  cfdiRelationship varchar(3) NULL,
  cfdiPaymentMethod varchar(3) NULL,
  cassOID varchar(40) NULL,
  transitItemAmount decimal(20,3) NULL,
  transitItemCurrency varchar(3) NULL,
  externalReferenceUpper varchar(255) NULL,
  paymentFileGenerated integer NOT NULL,
  externalIdentifier varchar(128) NULL,
  createIncomingCounterpart integer NOT NULL,
  createdByAPImport integer NOT NULL,
  onHoldTime datetime2(6) NULL,
  releasedTime datetime2(6) NULL,
  onHoldUser varchar(128) NULL,
  releasedUser varchar(128) NULL,
  toBeCheckedBy varchar(128) NULL,
  includeWaybill integer NOT NULL,
  internal integer NOT NULL);

-- SCOPE COST CENTERS --

CREATE TABLE dbo.mad_costcenter (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  code varchar(255) NOT NULL,
  validityStart date NULL,
  validityEnd date NULL,
  partnerOID varchar(40) NULL,
  name varchar(255) NULL,
  legalEntityOID varchar(40) NOT NULL,
  organizationOID varchar(40) NOT NULL,
  accountingCode varchar(32) NULL);

CREATE TABLE dbo.cus_customs_order (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  orderDate date NULL,
  remarks varchar(4000) NULL,
  orderer_OID varchar(40) NULL,
  supplier_OID varchar(40) NULL,
  economicDate date NULL,
  status varchar(64) NULL,
  type varchar(64) NOT NULL,
  clerk varchar(128) NULL,
  toBeBilled integer NOT NULL,
  country varchar(2) NULL,
  product_OID varchar(40) NULL,
  salesPerson_OID varchar(40) NULL,
  transportMode varchar(32) NULL,
  manualEconomicDate integer NOT NULL,
  rootOrderOID varchar(40) NULL,
  rootOrderMimeType varchar(255) NULL,
  statusText varchar(127) NULL,
  vorCusDocNumber varchar(63) NULL,
  vorCusDocType varchar(8) NULL,
  vorCusDocPos integer NULL,
  cancelled integer NOT NULL,
  cusDocNumber varchar(63) NULL,
  cusDocType varchar(8) NULL,
  cusDocPos integer NULL,
  dealDate date NULL,
  customsServiceId varchar(31) NULL,
  parentOrderOID varchar(40) NULL,
  parentOrderMimeType varchar(127) NULL,
  cancellationReason_OID varchar(40) NULL,
  salesCommissionAmount decimal(20,3) NULL,
  salesCommissionCurrency varchar(3) NULL,
  supplierPartnerOID varchar(40) NULL,
  positionsCount integer NULL,
  determinedTaxability varchar(32) NULL,
  conveyanceType varchar(32) NULL);

CREATE TABLE dbo.scp_localized_string (
  OID varchar(40) NOT NULL,
  defaultStringOID varchar(40) NULL,
  language varchar(32) NULL,
  value VARCHAR(1000));

CREATE TABLE dbo.mad_air_carrier (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  awbPrefix varchar(3) NULL,
  iataCode varchar(2) NULL,
  icaoCode varchar(3) NULL,
  name varchar(255) NULL,
  deactivated integer NOT NULL,
  urn varchar(128) NOT NULL,
  pp_name varchar(255) NULL,
  pp_labels VARCHAR(1000),
  pp_language varchar(32) NULL,
  pp_business integer NOT NULL,
  defaultAddress_OID varchar(40) NOT NULL,
  awbCarrierAddress varchar(140) NULL);

CREATE TABLE dbo.mad_carrier_road (
  OID varchar(40) NOT NULL,
  changeTime datetime2(6) NOT NULL,
  changer varchar(128) NOT NULL,
  creationTime datetime2(6) NOT NULL,
  creator varchar(128) NOT NULL,
  partner_OID varchar(40) NULL,
  deactivated integer NOT NULL,
  cmrAddress varchar(180) NULL,
  volumeFactor decimal(19,3) NULL,
  ediCustomer_OID varchar(40) NULL,
  scac varchar(4) NULL,
  ediEnableUpdates integer 1,
  ediEnableDocuments integer 0);

